window.VA = {
 "site": {
  "name": "St. Jerome Cemetery",
  "title": "St. Jerome Cemetery Veterans Memorial",
  "address": "125 Saint Jerome Avenue, Holyoke, MA",
  "kind": "cemetery",
  "center": [
   42.2052,
   -72.6255
  ],
  "zoom": 17
 },
 "veterans": [
  {
   "id": "sj_mooney_james_l_sr",
   "name": "James L. Mooney Sr.",
   "era": "Korea",
   "branch": "U.S. Air Force",
   "branchLabel": "Air Force · Korea",
   "lat": 42.2052,
   "lng": -72.6258,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/mooney_james_l_sr.jpg",
   "extraPhotos": [],
   "narrative": "James L. Mooney Sr. served as a Staff Sergeant in the United States Air Force during the Korean War. His marker at St. Jerome Cemetery remembers him as a beloved husband, father, grandfather, and brother (1933–2023). If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_ripa_louis_j",
   "name": "Louis J. Ripa",
   "era": "World War II",
   "branch": "U.S. Navy",
   "branchLabel": "Navy · WWII",
   "lat": 42.2052,
   "lng": -72.62525,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/ripa_louis_j.jpg",
   "extraPhotos": [],
   "narrative": "Louis J. Ripa served as an Aviation Ordnanceman Second Class in the United States Navy during World War II (1911–1992). If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_mckenzie_t",
   "name": "T. McKenzie",
   "era": "World War I",
   "branch": "",
   "branchLabel": "",
   "lat": 42.2052,
   "lng": -72.6247,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/mckenzie_t.jpg",
   "extraPhotos": [],
   "narrative": "A veteran of the First World War surnamed McKenzie (first initial T.) rests at St. Jerome Cemetery, his service marked by a World War One veteran's star at the grave. The monument is partly obscured; further details await research. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_scollard",
   "name": "Scollard",
   "era": "World War II",
   "branch": "",
   "branchLabel": "",
   "lat": 42.2052,
   "lng": -72.62415,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/scollard.jpg",
   "extraPhotos": [],
   "narrative": "A member of the Scollard family who served in World War II rests beneath this monument at St. Jerome Cemetery, marked by a 1941–1945 World War II veteran's emblem. The given name is not shown on the family stone and awaits research. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_harnois_homer_j",
   "name": "Homer Joseph Harnois",
   "era": "World War II",
   "branch": "U.S. Navy",
   "branchLabel": "Navy · WWII",
   "lat": 42.20565,
   "lng": -72.6258,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/harnois_homer_j.jpg",
   "extraPhotos": [],
   "narrative": "Homer Joseph Harnois served as a Seaman First Class in the United States Navy during World War II (1921–2004). If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_gorman_louis_o",
   "name": "Louis O. Gorman",
   "era": "World War II",
   "branch": "U.S. Army",
   "branchLabel": "Army · WWII",
   "lat": 42.20565,
   "lng": -72.62525,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/gorman_louis_o.jpg",
   "extraPhotos": [],
   "narrative": "Louis O. Gorman served as a Private in the United States Army during World War II (1924–1991). If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_clarke_walter_j",
   "name": "Walter J. Clarke",
   "era": "World War II",
   "branch": "U.S. Navy",
   "branchLabel": "Navy · WWII",
   "lat": 42.20565,
   "lng": -72.6247,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/clarke_walter_j.jpg",
   "extraPhotos": [],
   "narrative": "Walter J. Clarke served as a Quartermaster Second Class in the United States Navy during World War II (1923–1990). If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_welch_edward_j",
   "name": "Edward J. Welch",
   "era": "World War I",
   "branch": "",
   "branchLabel": "",
   "lat": 42.20565,
   "lng": -72.62415,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/welch_edward_j.jpg",
   "extraPhotos": [],
   "narrative": "Edward J. Welch (1894–1918) rests in the Welch family plot at St. Jerome Cemetery. He died on January 15, 1918, during the First World War. He also appears in the research records among Holyoke's World War I men. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_mcintyre_patrick_f",
   "name": "Patrick F. McIntyre",
   "era": "World War II",
   "branch": "U.S. Army",
   "branchLabel": "Army · WWII",
   "lat": 42.2061,
   "lng": -72.6258,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/mcintyre_patrick_f.jpg",
   "extraPhotos": [],
   "narrative": "Patrick F. McIntyre served as a Private First Class in the United States Army during World War II. His marker at St. Jerome Cemetery is shared with family under the words “Always Together.” If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  },
  {
   "id": "sj_kaeble_raymond_r",
   "name": "Raymond R. Kaeble",
   "era": "World War II",
   "branch": "U.S. Army Air Forces",
   "branchLabel": "Army Air Forces · WWII",
   "lat": 42.2061,
   "lng": -72.62525,
   "geo": "provisional",
   "photo": "/Veteran-Archives/photos/st-jerome/kaeble_raymond_r.jpg",
   "extraPhotos": [],
   "narrative": "Raymond R. Kaeble served as a Staff Sergeant in the United States Army Air Forces during World War II (1923–1986). His marker gives the branch in its wartime form, Army Air Corps. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "st-jerome-field-batch1"
  }
 ]
};
