window.VA = {
 "site": {
  "name": "Elmwood Cemetery",
  "title": "Elmwood Cemetery Veterans Memorial",
  "address": "493 Northampton Street, Holyoke, MA",
  "kind": "cemetery",
  "center": [
   42.1869,
   -72.6291
  ],
  "zoom": 17,
  "nameField": "bio"
 },
 "veterans": [
  {
   "id": "aaron_f_baldwin_cw",
   "name": "Aaron F. Baldwin",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187094,
   "lng": -72.629106,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Baldwin.jpg",
   "extraPhotos": [],
   "narrative": "Aaron F. Baldwin served as a soldier in the Union Army during the Civil War, assigned to Company F of the 27th Massachusetts Volunteer Infantry. The 27th Massachusetts saw action across multiple theaters of the war, including service in North Carolina and Virginia. Baldwin returned to Holyoke, where he is buried alongside his family at Elmwood Cemetery. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "carlton_r_baush_wwi",
   "name": "Carlton R. Baush",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187072,
   "lng": -72.629203,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/C Baush.jpg",
   "extraPhotos": [],
   "narrative": "Carlton R. Baush served as a Sergeant in Company C of the 321st Machine Gun Battalion during World War I. The 321st Machine Gun Battalion was assigned to the 164th Infantry Brigade of the 82nd Division — the All-American Division, so named because its draftees came from all 48 states. The 82nd deployed to France in 1918 and fought in the Lorraine campaign, the Battle of St. Mihiel, and the Meuse-Argonne Offensive — one of the largest military operations in American history. Machine gun battalions provided the sustained defensive fire that anchored infantry positions on the Western Front. Baush was born February 20, 1896 and died May 30, 1965. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lo_carpenter_cw",
   "name": "L.O. Carpenter",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187439,
   "lng": -72.629928,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Carpenter.jpg",
   "extraPhotos": [],
   "narrative": "L.O. Carpenter served as a First Lieutenant and Assistant Surgeon with the 57th Massachusetts Volunteer Infantry during the Civil War. Military surgeons operated under fire, performing amputations and field medicine that saved countless lives under conditions of extreme hardship. The 57th Massachusetts was organized in 1864 and saw heavy combat in the Overland Campaign under General Grant. A Grand Army of the Republic marker stands at his grave, recognizing his Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "patrick_j_curran_wwi",
   "name": "Patrick J. Curran",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186917,
   "lng": -72.629203,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Curren.jpg",
   "extraPhotos": [],
   "narrative": "Patrick J. Curran served as a Sergeant in Company C of the 336th Battalion, Tank Corps, during World War I. The Tank Corps was established by the American Expeditionary Forces in 1917, with Captain George S. Patton among its first officers, to deploy the new technology of armored warfare on the Western Front. A total of 29 tank battalions were raised, but the armistice of November 1918 came before most of them could reach the front — only four Tank Corps battalions saw combat. Curran's unit was among those that trained and prepared but did not reach the fighting line before the war ended. The Tank Corps was formally disbanded in 1920. Curran was born March 12, 1892 and died December 5, 1965. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "edward_day_rev",
   "name": "Edward Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187144,
   "lng": -72.629197,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Day.jpg",
   "extraPhotos": [],
   "narrative": "Edward Day died on October 25, 1777, at the age of 19, during the Revolutionary War. He was the fourth of eleven children born to Joel and Eunice Day of Holyoke, a family that gave more than most to the struggle for independence: Joel Day and five of his sons served, and two of those sons did not come home. Edward died at Troy, New York, wounded in a skirmish and taken by illness within days. His younger brother Robert had died two months earlier, ambushed while carrying supplies to American forces near Ticonderoga. Both brothers are commemorated on the Joel Day family stone at Elmwood Cemetery, one of the most significant Revolutionary War memorials in the Pioneer Valley. Eunice Day, their mother, is honored by a Daughters of the American Revolution tablet for her family’s sacrifice. The DAR chapter in Holyoke named itself the Eunice Day Chapter in her memory. The stone at Elmwood stands as a record of what this city gave, at the very beginning of the American republic, in the persons of two sons who did not return. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "robert_day_rev",
   "name": "Robert Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629197,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Day.jpg",
   "extraPhotos": [],
   "narrative": "Robert Day was 13 years old when he was killed on August 27, 1777, ambushed while carrying supplies and food to American forces near Ticonderoga, New York. He was the sixth child of Joel and Eunice Day of Holyoke, a family whose service to the Revolutionary cause was extraordinary: Joel Day and five of his sons served, and Robert and his brother Edward both died in 1777, two months apart. Robert was not an enlisted soldier — he was a boy in service to his country’s cause, and he did not come home. His brother Edward died that same October at Troy, New York. Both are recorded on the Joel Day family stone at Elmwood Cemetery, one of the oldest and most consequential markers in the Pioneer Valley. Their mother Eunice Day is honored by a Daughters of the American Revolution tablet for what she gave to the founding of this nation. Robert’s age and the circumstances of his death make his story one of the most striking in Elmwood Cemetery. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "william_r_dempsey_wwii",
   "name": "William R. Dempsey",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.628631,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/dempsey.jpg",
   "extraPhotos": [],
   "narrative": "William R. Dempsey served as a Pharmacist's Mate First Class in the United States Navy during World War II. Navy pharmacist's mates served as frontline medical corpsmen, providing emergency medical care aboard ships and with Marine units under combat conditions. Dempsey was born August 2, 1925 and died November 23, 1998. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "hugo_dudman_wwi_wwii",
   "name": "Hugo Dudman",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187114,
   "lng": -72.629281,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/dudman.jpg",
   "extraPhotos": [],
   "narrative": "Hugo Dudman served as a Signalman Second Class in the United States Navy through both World War I and World War II — a rare distinction that spans more than two decades of naval service. Signalmen were responsible for visual communications between vessels, a critical role before the era of reliable radio. Dudman was born July 28, 1897 and died April 28, 1946, shortly after the close of World War II. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "elisha_chapin_colonial",
   "name": "Elisha Chapin",
   "era": "French & Indian War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187378,
   "lng": -72.629561,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/E Chapin.jpg",
   "extraPhotos": [],
   "narrative": "Captain Elisha Chapin, born July 16, 1707, was a provincial militia officer who commanded Fort Massachusetts — the westernmost fortification in the line of forts defending British colonial Massachusetts — from 1752 to 1754. Fort Massachusetts stood on the Hoosac River frontier of Berkshire County, the last organized defense against French and Indian forces moving south from Canada. Chapin served on the most exposed edge of the British colonial world, in a region where raids, ambushes, and sudden death were facts of daily life. On July 11, 1756, while searching for strayed cattle near Hemlock Brook at West Hoosac — the settlement that would become Williamstown — Chapin was killed by a party of Native warriors. The attack occurred as the French and Indian War was escalating across the Western Massachusetts frontier. Chapin’s marker is among the oldest military gravestones in the region. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "KIA"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "jno_eveleth_cw",
   "name": "John Eveleth",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186958,
   "lng": -72.629272,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/eveleth.jpg",
   "extraPhotos": [],
   "narrative": "John Eveleth — listed on his marker as Jno. Eveleth — served with the 15th Massachusetts Battery during the Civil War. The 15th Massachusetts Battery was a light artillery unit that served in the Eastern Theater, providing cannon support in engagements across Virginia and Maryland. Artillery units like the 15th were essential to Union battlefield tactics, delivering fire that could determine the outcome of an engagement. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "arthur_emil_ezold_wwii",
   "name": "Arthur Emil Ezold",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186986,
   "lng": -72.629242,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/ezold.jpg",
   "extraPhotos": [],
   "narrative": "Arthur Emil Ezold served as a Sergeant in the 1460th Service Command Unit of the United States Army during World War II. Service command units were the logistical backbone of the American war effort, managing the supply chains, depots, and transport networks that kept combat forces equipped and operational across multiple theaters. Ezold was born June 15, 1906 and died September 27, 1967. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "fred_k_burnham_cw",
   "name": "Frederick K. Burnham",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.629058,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/F Burnham.jpg",
   "extraPhotos": [],
   "narrative": "Frederick K. Burnham — recorded on his marker as Fred'k Burnham — served in Company I of the 10th Massachusetts Volunteer Infantry during the Civil War. The 10th Massachusetts saw action in some of the war's most consequential engagements, including the Peninsular Campaign, Antietam, and the Overland Campaign. A GAR marker stands at his grave, placed by the Grand Army of the Republic in recognition of his Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "david_w_mulligan_unk",
   "name": "David W. Mulligan",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187531,
   "lng": -72.628983,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/D Mulligan.jpg",
   "extraPhotos": [],
   "narrative": "David W. Mulligan was born in 1918 and died in 1965, having lived through both World War II and the Korean War era. An American flag marks his grave at Elmwood Cemetery, confirming his veteran status. Men born in 1918 were of prime service age when the United States entered World War II in December 1941, and Mulligan would have been 23 years old at the time of Pearl Harbor. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "oswald_f_friedrich",
   "name": "Oswald F. Friedrich",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.628983,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Friedrich.jpg",
   "extraPhotos": [],
   "narrative": "Oswald F. Friedrich was born in 1862 and died in 1947, having lived through the Civil War, the Spanish-American War, both World Wars, and into the postwar era. A U.S. veteran marker stands at his grave at Elmwood Cemetery. Born in 1862, Friedrich was of enlistment age during the Spanish-American War of 1898 and may also have served during the era of the Philippine Insurrection that followed. His specific branch of service and unit have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "george_a_baush_wwii",
   "name": "George A. Baush",
   "era": "World War II",
   "branch": "Coast Guard",
   "branchLabel": "",
   "lat": 42.187089,
   "lng": -72.62915,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/G Baush.jpg",
   "extraPhotos": [],
   "narrative": "George A. Baush served in the United States Coast Guard during World War II. The Coast Guard's wartime mission expanded dramatically after Pearl Harbor: its cutters and crews escorted convoys across the North Atlantic, conducted amphibious landings including D-Day and the Pacific island campaigns, and maintained port security along the American coastline. Coast Guardsmen crewed many of the landing craft that carried troops ashore at Normandy, Guadalcanal, and Iwo Jima — among the most dangerous assignments of the war. Baush was born January 2, 1928 and died October 15, 2015. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "g_burnham_cw",
   "name": "G. Burnham",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.629036,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/G Burnham.jpg",
   "extraPhotos": [],
   "narrative": "G. Burnham served as a Musician in Company I of the 10th Massachusetts Volunteer Infantry during the Civil War. Regimental musicians kept time on the march and relayed battlefield commands through drum signals under fire. The 10th Massachusetts saw action in some of the war's most consequential campaigns. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "gooley_unknown",
   "name": "Gooley",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187422,
   "lng": -72.629144,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Gooley.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read clearly. An American flag marks the grave, confirming veteran status. Name may be Gooley. Branch of service and era have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "harold_c_baush_wwii",
   "name": "Harold C. Baush",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187056,
   "lng": -72.62925,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/H Baush.jpg",
   "extraPhotos": [],
   "narrative": "Harold C. Baush served as a Technician Fifth Grade in the United States Army during World War II. The grade of Technician Fifth Class, or TEC 5, was introduced by the Army in 1942 to recognize soldiers with specialized technical skills — including mechanics, medics, radio operators, and supply specialists — who did not hold command responsibilities. TEC 5 soldiers were the trained backbone of Army logistics and support, keeping weapons, vehicles, and communications operational under combat conditions. Baush was born March 11, 1922 and died May 1, 2001. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "sa_hall_cw",
   "name": "S.A. Hall",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187461,
   "lng": -72.628814,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Hall.jpg",
   "extraPhotos": [],
   "narrative": "S.A. Hall served in Company B of the 46th Massachusetts Volunteer Infantry during the Civil War. The 46th Massachusetts was organized in the fall of 1862 as a nine-month regiment, one of many raised to meet the Union Army's urgent need for manpower following early setbacks in the war. It served in North Carolina under General John Foster, participating in operations aimed at disrupting Confederate supply lines and controlling the sounds and ports of the Carolina coast. The regiment mustered out in September 1863, having completed its term of service. A GAR marker at the grave recognizes Hall's Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "hupfer_unknown",
   "name": "Hupfer",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187003,
   "lng": -72.629211,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/hupper1.jpg",
   "extraPhotos": [],
   "narrative": "A U.S. War Veteran marker stands at the Hupfer family stone at Elmwood Cemetery. The specific veteran's first name, branch of service, and era have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "john_hynd_unknown",
   "name": "John Hynd",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187236,
   "lng": -72.629578,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Hynd.jpg",
   "extraPhotos": [],
   "narrative": "John Hynd was born August 18, 1893 and died February 20, 1971. An American flag marks his grave at Elmwood Cemetery, confirming his veteran status. Born in 1893, Hynd was 23 years old when the United States entered World War I in April 1917, placing him squarely within the generation that fought on the Western Front with the American Expeditionary Forces. He was also 48 years old at the time of Pearl Harbor, within the upper range of wartime service age. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "capt_joseph_day_rev",
   "name": "Joseph Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187106,
   "lng": -72.629914,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/J Day.jpg",
   "extraPhotos": [],
   "narrative": "Captain Joseph Day served during the Revolutionary War era and died March 19, 1813, aged 67 years. A member of the Day family of Holyoke — which gave multiple sons to the cause of American independence — Joseph Day may be related to Joel Day, whose stone commemorates the deaths of sons Edward and Robert in 1777. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "james_humeston_rev",
   "name": "James Humeston",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187344,
   "lng": -72.629303,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/J Humeston.jpg",
   "extraPhotos": [],
   "narrative": "James Humeston served during the Revolutionary War era and is honored at Elmwood Cemetery in Holyoke, where both an American flag and a Holyoke Lodge marker stand at his wife Martha's stone. The Connecticut River Valley contributed significantly to the Revolutionary War effort: Massachusetts militia units from this region served at Bunker Hill, in the defense of Boston, and in the northern campaigns that culminated in the American victory at Saratoga in 1777. James Humeston's specific regiment and dates of service have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "josiah_rogers_rev",
   "name": "Josiah Rogers",
   "era": "Revolutionary War",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187431,
   "lng": -72.629539,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/JosiahRogers.com.JPG",
   "extraPhotos": [],
   "narrative": "Deacon Josiah Rogers died in December 1792 in the 28th year of his age, as recorded on his stone at Elmwood Cemetery. His wife Sarah died in September 1779 at Waterbury, Connecticut. A veteran marker indicates military service connected to this grave. Born around 1764 and dying at 28, Rogers was of the generation that came of age during the Revolutionary War; if the veteran connection is to Rogers himself, he would have been a young soldier or militia member during the final years of the conflict. The specific nature of his service has not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "robert_alfred_krause_wwii",
   "name": "Robert Alfred Krause",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187417,
   "lng": -72.629311,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/krause.jpg",
   "extraPhotos": [],
   "narrative": "Robert Alfred Krause served as a Sergeant in the United States Army during World War II and was awarded the Purple Heart for wounds received in combat. The Purple Heart, authorized by George Washington in 1782, is awarded to members of the armed forces wounded or killed in action against an enemy of the United States. Receiving it as a Sergeant indicates Krause served in a leadership role at the squad or section level, typically responsible for a small group of men under fire. Krause was born February 11, 1918 and died November 1, 1991. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "Purple Heart"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lt_martin_chapin_rev",
   "name": "Martin Chapin",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187131,
   "lng": -72.629922,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/M Chapin.jpg",
   "extraPhotos": [],
   "narrative": "Lieutenant Martin Chapin died April 24, 1793, as recorded on his carved sandstone marker at Elmwood Cemetery — one of the most ornate early gravestones in the burial ground. The Chapin family had deep roots in the Connecticut River Valley stretching back to the founding generation of Springfield in the 1630s. Martin Chapin served as a lieutenant during the Revolutionary War era, in a family that produced multiple officers across several conflicts. His brother Elisha Chapin, also buried at Elmwood, was killed by Native warriors in 1756 during the French and Indian War. The specific regiment and engagements of Martin Chapin's service have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "jno_montgomery_cw",
   "name": "John Montgomery",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186914,
   "lng": -72.628739,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/montgomery.jpg",
   "extraPhotos": [],
   "narrative": "John Montgomery — listed on his marker as Jno. Montgomery — served in Company C of the 25th New Jersey Volunteer Infantry during the Civil War. The 25th New Jersey was organized in the fall of 1862 as a nine-month regiment, serving in the defenses around Washington before moving into Virginia and Maryland operations. Montgomery's burial in Holyoke suggests he settled in the Connecticut River Valley after the war, as many veterans did, drawn by the growing mill economy of the Pioneer Valley. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_1",
   "name": "Unknown Soldier 1",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629944,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/FMO?.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read. An American flag marks the grave, confirming veteran status. Name, branch, and era have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "capt_joseph_morgan_colonial",
   "name": "Joseph Morgan",
   "era": "French & Indian War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629706,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Morgan.jpg",
   "extraPhotos": [],
   "narrative": "Captain Joseph Morgan’s gravestone at Elmwood Cemetery records that he was “captured and included in the capitulation of Fort William Henry” in August 1757 — placing him at one of the most harrowing events of the French and Indian War. Fort William Henry stood at the southern end of Lake George in what is now New York, garrisoned by a British and provincial force under Lieutenant Colonel George Monro. In early August 1757, a French army of more than eight thousand men, including nearly two thousand Native warriors, surrounded the fort under General Montcalm. After six days of bombardment and no relief from the British commander at Fort Edward, Monro surrendered. Montcalm offered the garrison full honors of war and safe passage to Fort Edward. What followed was not safe passage. As the British column withdrew on August 10, Montcalm’s Indian allies, who had been promised plunder and were denied it by the terms of capitulation, attacked the evacuating soldiers, camp followers, women, and children. Scores were killed; hundreds were taken captive. Morgan was among those captured in the massacre. He survived, and he lived long enough to see the United States win its independence from the same British empire he had fought for as a young man. He died December 18, 1813, in the 78th year of his age. The events Morgan survived later became the backdrop for James Fenimore Cooper’s novel The Last of the Mohicans. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "richard_j_powers_navy",
   "name": "Richard J. Powers",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187325,
   "lng": -72.628822,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Powers.jpg",
   "extraPhotos": [],
   "narrative": "Richard J. Powers served as a Fireman First Class in the United States Navy. Born February 20, 1914 and died January 13, 1984, Powers served during the World War II era. Firemen in the Navy maintained the propulsion systems that kept ships underway in combat conditions. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "raymond_f_humeston_wwi",
   "name": "Raymond F. Humeston",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187397,
   "lng": -72.629342,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/R Humeston.jpg",
   "extraPhotos": [],
   "narrative": "Raymond F. Humeston served as a Private in the United States Army during World War I. He entered service on August 31, 1918, and was stationed at Camp Jackson, South Carolina — one of the great wartime training camps where hundreds of thousands of American soldiers were prepared for the front. Born in 1895, Humeston was among the young men of Holyoke who answered the call, though the armistice of November 1918 came before many of the late-summer draftees could ship overseas. He died in 1982, having lived nearly a century. He may be related to James Humeston, a Revolutionary War veteran also buried at Elmwood, though the connection is not confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "otto_ernest_riedel_wwii",
   "name": "Otto Ernest Riedel",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187381,
   "lng": -72.629272,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/riedel.jpg",
   "extraPhotos": [],
   "narrative": "Otto Ernest Riedel served as a Private in the United States Army during World War II. Born in 1911 and 30 years old at the time of Pearl Harbor, Riedel served within the broad mobilization that expanded the Army from fewer than 200,000 men in 1939 to more than eight million by 1945. Army Privates formed the essential foundation of that force, serving in every theater from North Africa to the Pacific. Riedel is buried in the Hupfer family plot at Elmwood Cemetery and died in 1985. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lawrence_w_robinson_wwii",
   "name": "Lawrence W. Robinson",
   "era": "World War II",
   "branch": "Army Air Forces",
   "branchLabel": "",
   "lat": 42.187458,
   "lng": -72.629836,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Robinson.jpg",
   "extraPhotos": [],
   "narrative": "Lawrence W. Robinson served as a Private First Class in the United States Army Air Forces during World War II. The Army Air Forces was the aerial warfare service of the United States during the war, predecessor to the modern Air Force. Robinson was born November 27, 1923 and died February 22, 2002. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "elsie_a_schenker_wwi",
   "name": "Elsie A. Schenker",
   "era": "World War I",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187319,
   "lng": -72.628722,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/schenker.jpg",
   "extraPhotos": [],
   "narrative": "Elsie A. Schenker served as a Yeoman Second Class — Yeoman (F) — in the United States Navy during World War I, making her among the first women in American history to serve in the military in a non-nursing capacity. The program began in March 1917, when Secretary of the Navy Josephus Daniels, finding no law requiring that a yeoman be a man, began enlisting women into the Naval Reserve. More than eleven thousand women ultimately served, popularly known as Yeomanettes — a nickname many of them disliked, preferring simply to be called Sailors. They worked as stenographers, bookkeepers, telephone operators, translators, fingerprint experts, and camouflage designers; a few served in France. They received equal pay with men of the same rank and served under the same military regulations. Schenker was born November 21, 1890 and died June 17, 1976. She is the only female veteran documented at Elmwood Cemetery. All Yeoman (F) enlistments formally ended in October 1920, and women would not serve in the uniformed Navy again until 1942. Elsie Schenker’s gravestone at Elmwood Cemetery is a record of a moment when the country asked something new of its women, and they answered. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "Female Veteran"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "alfred_b_sefton_wwii",
   "name": "Alfred B. Sefton",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187594,
   "lng": -72.629417,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/sefton.jpg",
   "extraPhotos": [],
   "narrative": "Alfred B. Sefton served as a Staff Sergeant in the United States Army. Born January 26, 1919, Sefton was 22 years old when the United States entered World War II in December 1941. Staff Sergeants served as non-commissioned officers leading rifle squads and weapons teams, typically in direct combat or close support roles. The rank carried significant responsibility: a Staff Sergeant was expected to keep his soldiers alive, maintain unit cohesion under fire, and execute orders when officers were not present. Sefton died September 19, 1999. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "william_f_tauscher_wwi",
   "name": "William F. Tauscher",
   "era": "World War I",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.186961,
   "lng": -72.629614,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/tauscher.jpg",
   "extraPhotos": [],
   "narrative": "William F. Tauscher served as a Cook in the United States Naval Reserve Force during World War I. The USNRF expanded rapidly after America entered the war in 1917, drawing men from across Massachusetts to serve in a variety of naval roles. Tauscher was born September 4, 1894 and died January 10, 1963. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_2",
   "name": "Unknown Soldier 2",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.18695,
   "lng": -72.629172,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/unknown vet 2.jpg",
   "extraPhotos": [],
   "narrative": "This Civil War veteran's stone at Elmwood Cemetery is too worn to read clearly. The standard Union Army shield marker shape and partial text suggest Massachusetts service. Name and unit have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_3",
   "name": "Unknown Soldier 3",
   "era": "Unknown Era",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187428,
   "lng": -72.629144,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/vet unknown3.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read clearly. An American flag marks the grave, confirming veteran status. Name and unit have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "ernest_j_hupfer",
   "name": "Ernest J. Hupfer",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187394,
   "lng": -72.629319,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/vetunknown4.jpg",
   "extraPhotos": [],
   "narrative": "Ernest J. Hupfer was born in 1883 and died in 1954. An American flag marks the Hupfer family stone at Elmwood Cemetery, indicating veteran status. Born in 1883, Hupfer was 34 years old when the United States entered World War I in 1917, within the eligible range for military service under the Selective Service Act of that year, which applied to men ages 21 to 31 at first registration, later expanded to 18 to 45. He may be the veteran recognized by the flag at this plot, though a second family member, also a veteran, is listed nearby. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "frank_h_wade",
   "name": "Frank H. Wade",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187133,
   "lng": -72.629953,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Wade Batchelor.jpg",
   "extraPhotos": [],
   "narrative": "Frank H. Wade was born in 1872 and died in 1952. An American flag marks his grave at Elmwood Cemetery, indicating veteran status. Born in 1872, Wade was 25 years old during the Spanish-American War of 1898 and 44 years old when the United States entered World War I in 1917, making Spanish-American War service the most likely era for his military service. Massachusetts contributed thousands of volunteers to the Spanish-American War, many of whom served in Cuba, Puerto Rico, and the Philippines. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "paul_f_wagner",
   "name": "Paul F. Wagner",
   "era": "World War I",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187386,
   "lng": -72.629539,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Wagner.jpg",
   "extraPhotos": [],
   "narrative": "Paul F. Wagner was born in 1889 and died in 1945. A veteran marker stands at his grave at Elmwood Cemetery. Born in 1889, Wagner was 27 years old when the United States entered World War I in April 1917, and was precisely within the first class of men to register under the Selective Service Act — men ages 21 to 31. Over 189,000 Massachusetts men and women served in the armed forces during World War I. Wagner died in 1945, the final year of World War II, though whether his death was related to wartime service has not been confirmed. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "allen_s_walker_wwii",
   "name": "Allen S. Walker",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187436,
   "lng": -72.628569,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/walker.jpg",
   "extraPhotos": [],
   "narrative": "Allen S. Walker served as a Technician Fourth Grade in the United States Army during World War II. TEC 4 was a specialist rank recognizing skilled technical work such as engineering, communications, or medical support. Walker was born May 11, 1911 and died May 29, 1996. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lo_white_cw",
   "name": "L.O. White",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187256,
   "lng": -72.629111,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/white.jbg.JPG",
   "extraPhotos": [],
   "narrative": "L.O. White served in Company B of the 46th Massachusetts Volunteer Infantry during the Civil War — the same regiment as fellow Elmwood Cemetery veteran S.A. Hall. The 46th Massachusetts was a nine-month regiment organized in 1862, serving in North Carolina. White's standard Union shield marker stands as one of several Civil War stones at Elmwood Cemetery. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_4",
   "name": "Unknown Soldier 4",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187156,
   "lng": -72.629953,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/RMDay.JPG",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read. An American flag marks the grave, confirming veteran status. The inscription is partially visible but not yet confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  }
 ]
};
