window.VA = {
 "site": {
  "name": "Elmwood Cemetery",
  "title": "Elmwood Cemetery Veterans Memorial",
  "address": "493 Northampton Street, Holyoke, MA",
  "kind": "cemetery",
  "center": [
   42.1869,
   -72.6291
  ],
  "zoom": 17,
  "nameField": "bio"
 },
 "veterans": [
  {
   "id": "aaron_f_baldwin_cw",
   "name": "Aaron F. Baldwin",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187094,
   "lng": -72.629106,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Baldwin.jpg",
   "extraPhotos": [],
   "narrative": "Aaron F. Baldwin served as a soldier in the Union Army during the Civil War, assigned to Company F of the 27th Massachusetts Volunteer Infantry. The 27th Massachusetts saw action across multiple theaters of the war, including service in North Carolina and Virginia. Baldwin returned to Holyoke, where he is buried alongside his family at Elmwood Cemetery. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "carlton_r_baush_wwi",
   "name": "Carlton R. Baush",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187072,
   "lng": -72.629203,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/C Baush.jpg",
   "extraPhotos": [],
   "narrative": "Carlton R. Baush served as a Sergeant in Company C of the 321st Machine Gun Battalion during World War I. The 321st Machine Gun Battalion was assigned to the 164th Infantry Brigade of the 82nd Division — the All-American Division, so named because its draftees came from all 48 states. The 82nd deployed to France in 1918 and fought in the Lorraine campaign, the Battle of St. Mihiel, and the Meuse-Argonne Offensive — one of the largest military operations in American history. Machine gun battalions provided the sustained defensive fire that anchored infantry positions on the Western Front. Baush was born February 20, 1896 and died May 30, 1965. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lo_carpenter_cw",
   "name": "L.O. Carpenter",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187439,
   "lng": -72.629928,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Carpenter.jpg",
   "extraPhotos": [],
   "narrative": "L.O. Carpenter served as a First Lieutenant and Assistant Surgeon with the 57th Massachusetts Volunteer Infantry during the Civil War. Military surgeons operated under fire, performing amputations and field medicine that saved countless lives under conditions of extreme hardship. The 57th Massachusetts was organized in 1864 and saw heavy combat in the Overland Campaign under General Grant. A Grand Army of the Republic marker stands at his grave, recognizing his Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "patrick_j_curran_wwi",
   "name": "Patrick J. Curran",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186917,
   "lng": -72.629203,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Curren.jpg",
   "extraPhotos": [],
   "narrative": "Patrick J. Curran served as a Sergeant in Company C of the 336th Battalion, Tank Corps, during World War I. The Tank Corps was established by the American Expeditionary Forces in 1917, with Captain George S. Patton among its first officers, to deploy the new technology of armored warfare on the Western Front. A total of 29 tank battalions were raised, but the armistice of November 1918 came before most of them could reach the front — only four Tank Corps battalions saw combat. Curran's unit was among those that trained and prepared but did not reach the fighting line before the war ended. The Tank Corps was formally disbanded in 1920. Curran was born March 12, 1892 and died December 5, 1965. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "edward_day_rev",
   "name": "Edward Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187144,
   "lng": -72.629197,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Day.jpg",
   "extraPhotos": [],
   "narrative": "Edward Day was nineteen when he died on October 25, 1777, at Troy, New York, of smallpox. He was a son of Joel and Eunice Day of Holyoke, a family that gave more to the Revolution than most: the father and five sons served, and two of the sons did not come home. His name is cut into his father's stone at Elmwood — “Edward died in his Country's Service 25th Oct 1777, Æt. 19” — but he is not buried beneath it. Sarah Rusk's record says he died at Troy and is probably buried there; where he actually lies has not been established, and Rusk herself does not claim to know. An earlier version of this entry said he was wounded in a skirmish and taken by illness within days. That was wrong. The record says smallpox. A 1929 survey lists him in the thirteenth row from the South Drive, marker 9 — at his father's stone, not at a grave of his own. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "robert_day_rev",
   "name": "Robert Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629197,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Day.jpg",
   "extraPhotos": [],
   "narrative": "In the summer of 1777 a British army under Burgoyne was coming down from Canada by the lakes, and every farm in this valley was sending men and food north to meet it. Joel and Eunice Day had eleven children. Joel went. Five of his sons went. Eunice ran the farm. Ticonderoga is a hundred miles north of this valley, and in 1777 the road there was an ox-cart track for most of the way. The provisions parties were farmers and their sons with wagons, moving north for days behind an army that was living hand to mouth. Nobody enlisted them. Nobody paid them. The army ate because the farms sent food, and the farms sent boys with it. Robert Day was the sixth child of Joel and Eunice Day, having gone to Fort Ticonderoga with a party carrying provisions up to the army. He was not a soldier. He was a boy carrying food to men who needed it, and he did not come back. His name is cut into his father's stone beneath his brother Edward's. Robert Day “died 27 Aug 1777, Aged 13 Years”. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "william_r_dempsey_wwii",
   "name": "William R. Dempsey",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.628631,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/dempsey.jpg",
   "extraPhotos": [],
   "narrative": "William R. Dempsey served as a Pharmacist's Mate First Class in the United States Navy during World War II. Navy pharmacist's mates served as frontline medical corpsmen, providing emergency medical care aboard ships and with Marine units under combat conditions. Dempsey was born August 2, 1925 and died November 23, 1998. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "hugo_dudman_wwi_wwii",
   "name": "Hugo Dudman",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187114,
   "lng": -72.629281,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/dudman.jpg",
   "extraPhotos": [],
   "narrative": "Hugo Dudman served as a Signalman Second Class in the United States Navy through both World War I and World War II — a rare distinction that spans more than two decades of naval service. Signalmen were responsible for visual communications between vessels, a critical role before the era of reliable radio. Dudman was born July 28, 1897 and died April 28, 1946, shortly after the close of World War II. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "elisha_chapin_colonial",
   "name": "Elisha Chapin",
   "era": "French & Indian War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187378,
   "lng": -72.629561,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/E Chapin.jpg",
   "extraPhotos": [],
   "narrative": "Captain Elisha Chapin, born July 16, 1707, was a provincial militia officer who commanded Fort Massachusetts — the westernmost fortification in the line of forts defending British colonial Massachusetts — from 1752 to 1754. Fort Massachusetts stood on the Hoosac River frontier of Berkshire County, the last organized defense against French and Indian forces moving south from Canada. Chapin served on the most exposed edge of the British colonial world, in a region where raids, ambushes, and sudden death were facts of daily life. On July 11, 1756, while searching for strayed cattle near Hemlock Brook at West Hoosac — the settlement that would become Williamstown — Chapin was killed by a party of Native warriors. The attack occurred as the French and Indian War was escalating across the Western Massachusetts frontier. Chapin’s marker is among the oldest military gravestones in the region. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "KIA"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "jno_eveleth_cw",
   "name": "John Eveleth",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186958,
   "lng": -72.629272,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/eveleth.jpg",
   "extraPhotos": [],
   "narrative": "John Eveleth — listed on his marker as Jno. Eveleth — served with the 15th Massachusetts Battery during the Civil War. The 15th Massachusetts Battery was a light artillery unit that served in the Eastern Theater, providing cannon support in engagements across Virginia and Maryland. Artillery units like the 15th were essential to Union battlefield tactics, delivering fire that could determine the outcome of an engagement. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "arthur_emil_ezold_wwii",
   "name": "Arthur Emil Ezold",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186986,
   "lng": -72.629242,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/ezold.jpg",
   "extraPhotos": [],
   "narrative": "Arthur Emil Ezold served as a Sergeant in the 1460th Service Command Unit of the United States Army during World War II. Service command units were the logistical backbone of the American war effort, managing the supply chains, depots, and transport networks that kept combat forces equipped and operational across multiple theaters. Ezold was born June 15, 1906 and died September 27, 1967. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "fred_k_burnham_cw",
   "name": "Frederick K. Burnham",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.629058,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/F Burnham.jpg",
   "extraPhotos": [],
   "narrative": "Frederick K. Burnham — recorded on his marker as Fred'k Burnham — served in Company I of the 10th Massachusetts Volunteer Infantry during the Civil War. The 10th Massachusetts saw action in some of the war's most consequential engagements, including the Peninsular Campaign, Antietam, and the Overland Campaign. A GAR marker stands at his grave, placed by the Grand Army of the Republic in recognition of his Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "david_w_mulligan_unk",
   "name": "David W. Mulligan",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187531,
   "lng": -72.628983,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/D Mulligan.jpg",
   "extraPhotos": [],
   "narrative": "David W. Mulligan was born in 1918 and died in 1965, having lived through both World War II and the Korean War era. An American flag marks his grave at Elmwood Cemetery, confirming his veteran status. Men born in 1918 were of prime service age when the United States entered World War II in December 1941, and Mulligan would have been 23 years old at the time of Pearl Harbor. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "oswald_f_friedrich",
   "name": "Oswald F. Friedrich",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.628983,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Friedrich.jpg",
   "extraPhotos": [],
   "narrative": "Oswald F. Friedrich was born in 1862 and died in 1947, having lived through the Civil War, the Spanish-American War, both World Wars, and into the postwar era. A U.S. veteran marker stands at his grave at Elmwood Cemetery. Born in 1862, Friedrich was of enlistment age during the Spanish-American War of 1898 and may also have served during the era of the Philippine Insurrection that followed. His specific branch of service and unit have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "george_a_baush_wwii",
   "name": "George A. Baush",
   "era": "World War II",
   "branch": "Coast Guard",
   "branchLabel": "",
   "lat": 42.187089,
   "lng": -72.62915,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/G Baush.jpg",
   "extraPhotos": [],
   "narrative": "George A. Baush served in the United States Coast Guard during World War II. The Coast Guard's wartime mission expanded dramatically after Pearl Harbor: its cutters and crews escorted convoys across the North Atlantic, conducted amphibious landings including D-Day and the Pacific island campaigns, and maintained port security along the American coastline. Coast Guardsmen crewed many of the landing craft that carried troops ashore at Normandy, Guadalcanal, and Iwo Jima — among the most dangerous assignments of the war. Baush was born January 2, 1928 and died October 15, 2015. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "g_burnham_cw",
   "name": "G. Burnham",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187283,
   "lng": -72.629036,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/G Burnham.jpg",
   "extraPhotos": [],
   "narrative": "G. Burnham served as a Musician in Company I of the 10th Massachusetts Volunteer Infantry during the Civil War. Regimental musicians kept time on the march and relayed battlefield commands through drum signals under fire. The 10th Massachusetts saw action in some of the war's most consequential campaigns. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "gooley_unknown",
   "name": "Gooley",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187422,
   "lng": -72.629144,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Gooley.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read clearly. An American flag marks the grave, confirming veteran status. Name may be Gooley. Branch of service and era have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "harold_c_baush_wwii",
   "name": "Harold C. Baush",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187056,
   "lng": -72.62925,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/H Baush.jpg",
   "extraPhotos": [],
   "narrative": "Harold C. Baush served as a Technician Fifth Grade in the United States Army during World War II. The grade of Technician Fifth Class, or TEC 5, was introduced by the Army in 1942 to recognize soldiers with specialized technical skills — including mechanics, medics, radio operators, and supply specialists — who did not hold command responsibilities. TEC 5 soldiers were the trained backbone of Army logistics and support, keeping weapons, vehicles, and communications operational under combat conditions. Baush was born March 11, 1922 and died May 1, 2001. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "sa_hall_cw",
   "name": "S.A. Hall",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187461,
   "lng": -72.628814,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Hall.jpg",
   "extraPhotos": [],
   "narrative": "S.A. Hall served in Company B of the 46th Massachusetts Volunteer Infantry during the Civil War. The 46th Massachusetts was organized in the fall of 1862 as a nine-month regiment, one of many raised to meet the Union Army's urgent need for manpower following early setbacks in the war. It served in North Carolina under General John Foster, participating in operations aimed at disrupting Confederate supply lines and controlling the sounds and ports of the Carolina coast. The regiment mustered out in September 1863, having completed its term of service. A GAR marker at the grave recognizes Hall's Union service. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "hupfer_unknown",
   "name": "Hupfer",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187003,
   "lng": -72.629211,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/hupper1.jpg",
   "extraPhotos": [],
   "narrative": "A U.S. War Veteran marker stands at the Hupfer family stone at Elmwood Cemetery. The specific veteran's first name, branch of service, and era have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "john_hynd_unknown",
   "name": "John Hynd",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187236,
   "lng": -72.629578,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Hynd.jpg",
   "extraPhotos": [],
   "narrative": "John Hynd was born August 18, 1893 and died February 20, 1971. An American flag marks his grave at Elmwood Cemetery, confirming his veteran status. Born in 1893, Hynd was 23 years old when the United States entered World War I in April 1917, placing him squarely within the generation that fought on the Western Front with the American Expeditionary Forces. He was also 48 years old at the time of Pearl Harbor, within the upper range of wartime service age. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "capt_joseph_day_rev",
   "name": "Joseph Day",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187106,
   "lng": -72.629914,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/J Day.jpg",
   "extraPhotos": [],
   "narrative": "Captain Joseph Day went to the war as a private, in Captain Joseph Morgan's company of Colonel John Moseley's regiment — out from October 21 to November 17, 1776, twenty-eight days to reinforce the Northern Army under Lieutenant Colonel Timothy Robinson of Granville, the roll dated at West Springfield. He was out again with the same company from September 21 to October 17, 1777: one month and three days on the expedition to the northern department. The rank on his stone came later; the rolls have him a private. His brownstone at Elmwood, carved with an urn and willow, records that he died March 19, 1813, aged 67, and carries also Mrs. Azubah Day, his consort, who died December 11, 1786, aged 37 — twenty-seven years before him. A newspaper account of the Day family wonders whether he might have been the father of Eunice Day. He cannot have been: Eunice was eleven years his senior. A 1929 survey placed him in the fifteenth row from the South Drive, marker 14. He was formerly carried in this archive twice — once from the survey of his stone and once from a list of Revolutionary graves. The two are one man, and the duplicate has been removed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "james_humeston_rev",
   "name": "James Humeston",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187344,
   "lng": -72.629303,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/J Humeston.jpg",
   "extraPhotos": [],
   "narrative": "James Humeston served during the Revolutionary War era and is honored at Elmwood Cemetery in Holyoke, where both an American flag and a Holyoke Lodge marker stand at his wife Martha's stone. The Connecticut River Valley contributed significantly to the Revolutionary War effort: Massachusetts militia units from this region served at Bunker Hill, in the defense of Boston, and in the northern campaigns that culminated in the American victory at Saratoga in 1777. James Humeston's specific regiment and dates of service have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "josiah_rogers_rev",
   "name": "Josiah Rogers",
   "era": "Revolutionary War",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187431,
   "lng": -72.629539,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/JosiahRogers.com.JPG",
   "extraPhotos": [],
   "narrative": "Deacon Josiah Rogers died in December 1792 in the 28th year of his age, as recorded on his stone at Elmwood Cemetery. His wife Sarah died in September 1779 at Waterbury, Connecticut. A veteran marker indicates military service connected to this grave. Born around 1764 and dying at 28, Rogers was of the generation that came of age during the Revolutionary War; if the veteran connection is to Rogers himself, he would have been a young soldier or militia member during the final years of the conflict. The specific nature of his service has not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "robert_alfred_krause_wwii",
   "name": "Robert Alfred Krause",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187417,
   "lng": -72.629311,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/krause.jpg",
   "extraPhotos": [],
   "narrative": "Robert Alfred Krause served as a Sergeant in the United States Army during World War II and was awarded the Purple Heart for wounds received in combat. The Purple Heart, authorized by George Washington in 1782, is awarded to members of the armed forces wounded or killed in action against an enemy of the United States. Receiving it as a Sergeant indicates Krause served in a leadership role at the squad or section level, typically responsible for a small group of men under fire. Krause was born February 11, 1918 and died November 1, 1991. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "Purple Heart"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lt_martin_chapin_rev",
   "name": "Martin Chapin",
   "era": "Revolutionary War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187131,
   "lng": -72.629922,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/M Chapin.jpg",
   "extraPhotos": [],
   "narrative": "Sergeant Martin Chapin served in Captain Joseph Morgan's company of Colonel John Moseley's Hampshire County regiment. He enlisted July 21, 1776 and returned November 17 — twenty-eight days, marching under Lieutenant Colonel Timothy Robinson of Granville to reinforce the Northern Army, the roll dated at West Springfield. He went out again with the same company and regiment on September 21, 1777, discharged October 17: one month and three days, travel included, on the expedition to the northern department. He married Bathsheba Cooper in 1768. He died in April 1793, and his carved brownstone — a winged soul's head between two rosettes — is one of the most striking early stones in the burial ground. This entry formerly gave his rank as Lieutenant. Both Sarah Rusk's record of Revolutionary patriots and the stone itself say Sergeant, and the rank has been corrected here. A 1929 survey placed him in the eighteenth row from the South Drive, marker 15. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "jno_montgomery_cw",
   "name": "John Montgomery",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.186914,
   "lng": -72.628739,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/montgomery.jpg",
   "extraPhotos": [],
   "narrative": "John Montgomery — listed on his marker as Jno. Montgomery — served in Company C of the 25th New Jersey Volunteer Infantry during the Civil War. The 25th New Jersey was organized in the fall of 1862 as a nine-month regiment, serving in the defenses around Washington before moving into Virginia and Maryland operations. Montgomery's burial in Holyoke suggests he settled in the Connecticut River Valley after the war, as many veterans did, drawn by the growing mill economy of the Pioneer Valley. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_1",
   "name": "Unknown Soldier 1",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629944,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/FMO?.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read. An American flag marks the grave, confirming veteran status. Name, branch, and era have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "capt_joseph_morgan_colonial",
   "name": "Joseph Morgan",
   "era": "French & Indian War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187164,
   "lng": -72.629706,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Morgan.jpg",
   "extraPhotos": [],
   "narrative": "Captain Joseph Morgan’s gravestone at Elmwood Cemetery records that he was “captured and included in the capitulation of Fort William Henry” in August 1757 — placing him at one of the most harrowing events of the French and Indian War. Fort William Henry stood at the southern end of Lake George in what is now New York, garrisoned by a British and provincial force under Lieutenant Colonel George Monro. In early August 1757, a French army of more than eight thousand men, including nearly two thousand Native warriors, surrounded the fort under General Montcalm. After six days of bombardment and no relief from the British commander at Fort Edward, Monro surrendered. Montcalm offered the garrison full honors of war and safe passage to Fort Edward. What followed was not safe passage. As the British column withdrew on August 10, Montcalm’s Indian allies, who had been promised plunder and were denied it by the terms of capitulation, attacked the evacuating soldiers, camp followers, women, and children. Scores were killed; hundreds were taken captive. Morgan was among those captured in the massacre. He survived, and he lived long enough to see the United States win its independence from the same British empire he had fought for as a young man. He died December 18, 1813, in the 78th year of his age. The events Morgan survived later became the backdrop for James Fenimore Cooper’s novel The Last of the Mohicans. That is one war. There was a second. Rusk's record gives him a full Revolutionary service: commissioned captain of the 5th Company of Colonel John Moseley's regiment on April 30, 1776; captain of Lieutenant Colonel Timothy Robinson's detachment from Moseley's 3rd Hampshire regiment, engaged October 21, 1776 to march to Ticonderoga by order of General Schuyler, returned November 17, the roll dated at West Springfield; captain again under Colonel John Moseley from September 21 to October 17, 1777. A later turnout under Lieutenant Colonel David Moseley is recorded for a regiment raised for the support of government at Northampton — the call that answered Shays' Rebellion — but the year on the card cannot be read with confidence and is not given here. A local account says he gathered the first recruits of this place as soon as the war broke out, among them Lucas, Joseph M. 2nd, and Erastus Morgan, and that they became part of the Third Hampshire regiment. A survey of Revolutionary graves made under seal at Boston on November 14, 1929 lists him among the Revolutionary soldiers buried at Elmwood, marker 12, fourteenth row from the South Drive. This archive still carries him under the French and Indian War alone, on the evidence of his own stone. He appears to have fought in both wars, and the era on this entry awaits the ruling of the Veterans Graves Officer. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "richard_j_powers_navy",
   "name": "Richard J. Powers",
   "era": "World War II",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187325,
   "lng": -72.628822,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Powers.jpg",
   "extraPhotos": [],
   "narrative": "Richard J. Powers served as a Fireman First Class in the United States Navy. Born February 20, 1914 and died January 13, 1984, Powers served during the World War II era. Firemen in the Navy maintained the propulsion systems that kept ships underway in combat conditions. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "raymond_f_humeston_wwi",
   "name": "Raymond F. Humeston",
   "era": "World War I",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187397,
   "lng": -72.629342,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/R Humeston.jpg",
   "extraPhotos": [],
   "narrative": "Raymond F. Humeston served as a Private in the United States Army during World War I. He entered service on August 31, 1918, and was stationed at Camp Jackson, South Carolina — one of the great wartime training camps where hundreds of thousands of American soldiers were prepared for the front. Born in 1895, Humeston was among the young men of Holyoke who answered the call, though the armistice of November 1918 came before many of the late-summer draftees could ship overseas. He died in 1982, having lived nearly a century. He may be related to James Humeston, a Revolutionary War veteran also buried at Elmwood, though the connection is not confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "otto_ernest_riedel_wwii",
   "name": "Otto Ernest Riedel",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187381,
   "lng": -72.629272,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/riedel.jpg",
   "extraPhotos": [],
   "narrative": "Otto Ernest Riedel served as a Private in the United States Army during World War II. Born in 1911 and 30 years old at the time of Pearl Harbor, Riedel served within the broad mobilization that expanded the Army from fewer than 200,000 men in 1939 to more than eight million by 1945. Army Privates formed the essential foundation of that force, serving in every theater from North Africa to the Pacific. Riedel is buried in the Hupfer family plot at Elmwood Cemetery and died in 1985. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lawrence_w_robinson_wwii",
   "name": "Lawrence W. Robinson",
   "era": "World War II",
   "branch": "Army Air Forces",
   "branchLabel": "",
   "lat": 42.187458,
   "lng": -72.629836,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Robinson.jpg",
   "extraPhotos": [],
   "narrative": "Lawrence W. Robinson served as a Private First Class in the United States Army Air Forces during World War II. The Army Air Forces was the aerial warfare service of the United States during the war, predecessor to the modern Air Force. Robinson was born November 27, 1923 and died February 22, 2002. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "elsie_a_schenker_wwi",
   "name": "Elsie A. Schenker",
   "era": "World War I",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.187319,
   "lng": -72.628722,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/schenker.jpg",
   "extraPhotos": [],
   "narrative": "Elsie A. Schenker served as a Yeoman Second Class — Yeoman (F) — in the United States Navy during World War I, making her among the first women in American history to serve in the military in a non-nursing capacity. The program began in March 1917, when Secretary of the Navy Josephus Daniels, finding no law requiring that a yeoman be a man, began enlisting women into the Naval Reserve. More than eleven thousand women ultimately served, popularly known as Yeomanettes — a nickname many of them disliked, preferring simply to be called Sailors. They worked as stenographers, bookkeepers, telephone operators, translators, fingerprint experts, and camouflage designers; a few served in France. They received equal pay with men of the same rank and served under the same military regulations. Schenker was born November 21, 1890 and died June 17, 1976. She is the only female veteran documented at Elmwood Cemetery. All Yeoman (F) enlistments formally ended in October 1920, and women would not serve in the uniformed Navy again until 1942. Elsie Schenker’s gravestone at Elmwood Cemetery is a record of a moment when the country asked something new of its women, and they answered. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [
    "Female Veteran"
   ],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "alfred_b_sefton_wwii",
   "name": "Alfred B. Sefton",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187594,
   "lng": -72.629417,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/sefton.jpg",
   "extraPhotos": [],
   "narrative": "Alfred B. Sefton served as a Staff Sergeant in the United States Army. Born January 26, 1919, Sefton was 22 years old when the United States entered World War II in December 1941. Staff Sergeants served as non-commissioned officers leading rifle squads and weapons teams, typically in direct combat or close support roles. The rank carried significant responsibility: a Staff Sergeant was expected to keep his soldiers alive, maintain unit cohesion under fire, and execute orders when officers were not present. Sefton died September 19, 1999. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "william_f_tauscher_wwi",
   "name": "William F. Tauscher",
   "era": "World War I",
   "branch": "Navy",
   "branchLabel": "",
   "lat": 42.186961,
   "lng": -72.629614,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/tauscher.jpg",
   "extraPhotos": [],
   "narrative": "William F. Tauscher served as a Cook in the United States Naval Reserve Force during World War I. The USNRF expanded rapidly after America entered the war in 1917, drawing men from across Massachusetts to serve in a variety of naval roles. Tauscher was born September 4, 1894 and died January 10, 1963. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_2",
   "name": "Unknown Soldier 2",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.18695,
   "lng": -72.629172,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/unknown vet 2.jpg",
   "extraPhotos": [],
   "narrative": "This Civil War veteran's stone at Elmwood Cemetery is too worn to read clearly. The standard Union Army shield marker shape and partial text suggest Massachusetts service. Name and unit have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_3",
   "name": "Unknown Soldier 3",
   "era": "Unknown Era",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187428,
   "lng": -72.629144,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/vet unknown3.jpg",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read clearly. An American flag marks the grave, confirming veteran status. Name and unit have not yet been confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "ernest_j_hupfer",
   "name": "Ernest J. Hupfer",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187394,
   "lng": -72.629319,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/vetunknown4.jpg",
   "extraPhotos": [],
   "narrative": "Ernest J. Hupfer was born in 1883 and died in 1954. An American flag marks the Hupfer family stone at Elmwood Cemetery, indicating veteran status. Born in 1883, Hupfer was 34 years old when the United States entered World War I in 1917, within the eligible range for military service under the Selective Service Act of that year, which applied to men ages 21 to 31 at first registration, later expanded to 18 to 45. He may be the veteran recognized by the flag at this plot, though a second family member, also a veteran, is listed nearby. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "frank_h_wade",
   "name": "Frank H. Wade",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187133,
   "lng": -72.629953,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Wade Batchelor.jpg",
   "extraPhotos": [],
   "narrative": "Frank H. Wade was born in 1872 and died in 1952. An American flag marks his grave at Elmwood Cemetery, indicating veteran status. Born in 1872, Wade was 25 years old during the Spanish-American War of 1898 and 44 years old when the United States entered World War I in 1917, making Spanish-American War service the most likely era for his military service. Massachusetts contributed thousands of volunteers to the Spanish-American War, many of whom served in Cuba, Puerto Rico, and the Philippines. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "paul_f_wagner",
   "name": "Paul F. Wagner",
   "era": "World War I",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187386,
   "lng": -72.629539,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/Wagner.jpg",
   "extraPhotos": [],
   "narrative": "Paul F. Wagner was born in 1889 and died in 1945. A veteran marker stands at his grave at Elmwood Cemetery. Born in 1889, Wagner was 27 years old when the United States entered World War I in April 1917, and was precisely within the first class of men to register under the Selective Service Act — men ages 21 to 31. Over 189,000 Massachusetts men and women served in the armed forces during World War I. Wagner died in 1945, the final year of World War II, though whether his death was related to wartime service has not been confirmed. His branch of service and unit assignment have not yet been confirmed from available records. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "allen_s_walker_wwii",
   "name": "Allen S. Walker",
   "era": "World War II",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187436,
   "lng": -72.628569,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/walker.jpg",
   "extraPhotos": [],
   "narrative": "Allen S. Walker served as a Technician Fourth Grade in the United States Army during World War II. TEC 4 was a specialist rank recognizing skilled technical work such as engineering, communications, or medical support. Walker was born May 11, 1911 and died May 29, 1996. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "lo_white_cw",
   "name": "L.O. White",
   "era": "Civil War",
   "branch": "Army",
   "branchLabel": "",
   "lat": 42.187256,
   "lng": -72.629111,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/white.jbg.JPG",
   "extraPhotos": [],
   "narrative": "L.O. White served in Company B of the 46th Massachusetts Volunteer Infantry during the Civil War — the same regiment as fellow Elmwood Cemetery veteran S.A. Hall. The 46th Massachusetts was a nine-month regiment organized in 1862, serving in North Carolina. White's standard Union shield marker stands as one of several Civil War stones at Elmwood Cemetery. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "unknown_soldier_4",
   "name": "Unknown Soldier 4",
   "era": "Unknown Era",
   "branch": "Unknown",
   "branchLabel": "",
   "lat": 42.187156,
   "lng": -72.629953,
   "photo": "https://raw.githubusercontent.com/markwot-ops/elmwood-map/main/RMDay.JPG",
   "extraPhotos": [],
   "narrative": "This veteran's stone at Elmwood Cemetery is too worn to read. An American flag marks the grave, confirming veteran status. The inscription is partially visible but not yet confirmed. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "badges": [],
   "status": "located",
   "source": "elmwood-migrate"
  },
  {
   "id": "harper_rev_ball_charles",
   "name": "Ball, Charles",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Charles Ball of Holyoke served as a sergeant in the Revolutionary War. His people had been on this ground since about 1707, when his forebears Francis and Captain Eli Ball took up lots in the general area of what are now Northampton and Cherry Streets; the corner where the family lived was called Ball's Corner for many years afterward. A Ball planted the elm there in 1751 that was marked on maps of the day long after. In the early years, when raids were still feared, six families — the Balls, Chapins, Days, Elys, Millers and Morgans — would fort together at night for safety. Nearly every one of those names now lies within a few rows of him. He married Merab Miller, and died on July 3, 1838. Sarah Rusk's record of Revolutionary patriots gives his rank; his company and regiment have not yet been recovered, and that search continues. A 1929 survey of the burial ground placed his marble stone in the eighteenth row from the South Drive, marker 16. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_chapin_asahel",
   "name": "Chapin, Asahel",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Asahel Chapin was born in Wilbraham, a son of Stephen and Zebia Ely Chapin, and farmed in what is now Holyoke. When the alarm from Lexington reached the valley on April 19, 1775, he marched with Captain Enoch Chapin's company of Minutemen — eight days, and among the first men of this place to go. He went again in September 1777, in Captain Joseph Morgan's company of Colonel John Moseley's regiment: enlisted the 21st, discharged October 17, one month and three days including travel, on the expedition to the northern department. He married Sarah Frink in 1777. A son of his became the first pastor of the Second Baptist Church when it was formed in 1849 — twenty-one years after his father was in the ground. He died January 29, 1828. A 1929 survey placed his marble stone in the twelfth row from the South Drive, marker 6. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_day_jedediah",
   "name": "Day, Jedediah",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Jedediah Day, a son of Joel and Eunice Day, enlisted April 28, 1775 in Captain Enoch Chapin's company of Colonel Timothy Danielson's regiment and served three months and ten days. He was on the expedition to Ticonderoga from January 18 to April 3, 1777 — seventy-four days, through the worst of the winter. He served again under Captain Caleb Keep in Colonel William Shepard's regiment in 1778, and again from January to May of 1780. He came home; two of his brothers did not. He lived on the river bank where goods bound upriver for Ireland Parish were landed — when the water was low and the big ships could go no further, they unloaded there, and the farmers were called out with oxen, or horses in the winter, to cart the goods on to Northampton. In 1803 he was one of the men who met at Caleb Humeston's house on what is now Homestead Avenue to form the First Baptist Church. He died December 26, 1839. A 1929 survey placed his marble stone in the eleventh row from the South Drive, marker 4. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_day_joel",
   "name": "Day, Joel",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Joel Day, son of John Day and Abigail Bagg of West Springfield, marched on April 20, 1775 with Captain Enoch Chapin's company of Minutemen in response to the alarm of the day before — one month and five days. What followed was five more years of it. Captain Joseph Morgan's company, Colonel John Mosley's Hampshire regiment, October to November 1776, twenty-eight days to reinforce the Northern Army. Captain Daniel Cadwell's company, Colonel Timothy Robinson's detachment of Hampshire County militia, December 1776 to April 1777 — ninety-nine days, at Ticonderoga, where the muster roll of February 24, 1777 found him still in the garrison. Then Captain John Carpenter's company of guards at Springfield, three months at a stretch, over and over: March to June 1779, July to October 1779, October 1779 to January 1780, January to April 1780, and June to December 1780. He married Eunice Day, daughter of Joseph Day and Elizabeth Mattoon of Northfield, in 1751. Five of their sons served. Two did not come home. He died February 14, 1803, in his seventy-third year. His brownstone at Elmwood carries the names of Edward and Robert beneath his own — the only stone either boy has. His service above is taken from the Commonwealth's own rolls, Massachusetts Soldiers and Sailors in the War of the Revolution. A 1929 survey placed him in the thirteenth row from the South Drive, marker 8. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_day_joel_jr",
   "name": "Day, Joel, Jr.",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Joel Day, Jr., eldest son of Joel and Eunice Day, marched May 10, 1777 with Captain Salmon White's company of Colonel David Wells's regiment and served two months and ten days, travel included, on the expedition to Ticonderoga. In September he went out again, with Captain Seth Murray's company of Colonel Ezra May's regiment — one month, travel included, on the expedition to Saratoga, the campaign that ended in Burgoyne's surrender and brought France into the war. He came home. His brothers Edward and Robert did not. He died March 13, 1830, in his seventy-ninth year. His service is recorded in the Commonwealth's own rolls, Massachusetts Soldiers and Sailors in the War of the Revolution. A 1929 survey placed his marble stone in the twentieth row from the South Drive, marker 18. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_ely_benjamin",
   "name": "Ely, Benjamin",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Benjamin Ely was commissioned a major on February 8, 1776, in Colonel John Moseley's 3rd Hampshire regiment. He marched from home on October 21 that year and returned November 17 — twenty-eight days, his detachment going to Ticonderoga to reinforce the army by order of General Schuyler. He was a man of consequence here before ever he was a soldier. He was prominent in the town's affairs and served in the state legislature, and in 1773 he sat on the committee that sought to set this place off from West Springfield — the beginning of the long argument that eventually made Holyoke. For many years he kept a tavern in the Ingleside section, and it was on his farm that the last of the Indians in this area was allowed to live out his years. Rusk's record gives his rank as Major. His stone says Colonel. Both may be true of a long life in the militia, and the two have not been reconciled; both are set down here rather than one chosen. He died December 23, 1802, aged 72. A 1929 survey placed his brownstone in the twelfth row from the South Drive, marker 7. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_ely_enoch",
   "name": "Ely, Enoch",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Enoch Ely enlisted on April 28, 1775, nine days after the alarm from Lexington, in Captain Enoch Chapin's company of Colonel Timothy Danielson's regiment, and served until the first of August — three months and ten days, the summer the siege of Boston was laid. He went out again from September 21 to October 17, 1777, in Captain Joseph Morgan's company of Colonel John Moseley's regiment: one month and three days on the expedition to the northern department. He held the land on Tannery Brook, and was the first owner of the house later known as the Old Brown House, after Horace Brown took it over. He died in 1842, sixty-seven years after he first marched. A 1929 survey placed his marble stone in the fourteenth row from the South Drive, marker 11. His service is taken from Sarah Rusk's 1980 record of Revolutionary patriots and their wives buried in Holyoke, reproduced by Canal Days. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_ely_joseph",
   "name": "Ely, Joseph",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Joseph Ely enlisted July 9, 1777 in Captain Nathan Rowley's company of Colonel John Moseley's regiment and was discharged on the 29th — twenty-one days, the company marching to reinforce the Northern Army. A family account names him one of the founders of the First Baptist Church and says he married Martha Chapin Smith. He died on June 19, 1850, aged ninety-three years and eight months. Seventy-three years lay between those twenty-one days and his death — long enough to see the canals cut and the mills rise on ground he had known as farmland. A 1929 survey placed his marble stone in the eleventh row from the South Drive, marker 5. His service is taken from Sarah Rusk's 1980 record of Revolutionary patriots and their wives buried in Holyoke, reproduced by Canal Days. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_ely_jube",
   "name": "Ely, Jube",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Jube Ely enlisted July 28, 1779 in Captain Preserved Leonard's company of Colonel Elisha Porter's regiment and served one month and ten days at New London, Connecticut. The following year he was on the list of men raised to reinforce the Continental Army for a term of six months: he marched August 4, 1780 and was discharged December 15 — four months and seventeen days. He had a house on Northampton Street, shown on the map of 1827. Rusk's record and the 1929 survey of the burial ground both give the year of his death as 1843; a newspaper account of the Ely family says 1841. The two have not been reconciled and both are set down here. A 1929 survey placed his marble stone in the seventh row from the South Drive, marker 1 — the first of the twenty-one. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_fairfield_levi",
   "name": "Fairfield, Levi",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Levi Fairfield fought in the Revolutionary War and died in 1817. A local account says plainly that little is known of him, and that is still true: his company, his regiment and his dates have not been recovered from the record. What is known is where he lies. A 1929 survey placed his marble stone in the twenty-second row from the South Drive, marker 19. The search for the rest of him continues. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_hitchcock_peresh",
   "name": "Hitchcock, Peresh",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Peresh Hitchcock served in the Revolutionary War and died in 1831; his company, his regiment and his dates have not yet been recovered from the record. What is known is the life he built afterward. In 1803 he was one of the men who met at Caleb Humeston's house to help establish the Baptist Church; in 1805 he moderated a school meeting, and he was among those who established the Baptist Seminary. The map of 1827 shows him living on the Southampton Road near Rock Valley Road. He is said to have raised fourteen hundred bushels of rye in a single year, worth a dollar a bushel and a great deal of money then — so much rye, early historians said, that it led to the manufacture of whiskey, and the old map shows a distillery on Broad Brook in the Rock Valley section, right by the old school. His given name may stand in other records as Perez or Peris, which is one reason he is hard to find, and a caution against matching him to any similar name without proof. A 1929 survey placed his marble stone in the ninth row from the South Drive, marker 3. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_jones_ebenezer",
   "name": "Jones, Ebenezer",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Ebenezer Jones enlisted August 12, 1777 in Captain Ephraim Chapin's company of Colonel Ruggles Woodbridge's regiment and was discharged October 23 — two months and seventeen days under General Gates with the Northern Army, including five days and a hundred miles walking home. Those are the dates of Saratoga. He was with Gates through the campaign that broke Burgoyne and brought France into the war, and then he walked back to this valley. The roll was sworn to in Hampshire County. He died April 26, 1839, aged 90. Chicopee historians write of an Ebenezer Jones who in 1753 was paid for a drum of his that had been used, in the words of the record, to be beat to call the People to meeting at proper seasons; when the drum finally broke the people used a conch shell instead. Whether that man was this man, or his father, has not been established. A 1929 survey placed his marble stone in the twenty-fifth row from the South Drive, marker 20. His service is taken from Sarah Rusk's 1980 record of Revolutionary patriots and their wives buried in Holyoke, reproduced by Canal Days. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_miller_abner",
   "name": "Miller, Abner",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Abner Miller served in the Revolutionary War and died in 1829. The Millers were one of the six families — with the Balls, Chapins, Days, Elys and Morgans — who forted together at night in the years when raids were still feared, and Charles Ball, buried ten rows from him, married a Merab Miller. Whether Abner belonged to that household is not established and should not be assumed. His company, regiment and dates have not yet been recovered. A 1929 survey placed his marble stone in the eighth row from the South Drive, marker 2. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_morgan_jesse",
   "name": "Morgan, Jesse",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Jesse Morgan marched in April 1775 with Captain Enoch Chapin's company of Minutemen answering the alarm from Lexington — five days. He went out again from September 20 to October 17, 1777 in Captain Joseph Morgan's company of Colonel John Moseley's regiment: one month and three days on the expedition to the northern department, six of those days and a hundred and twenty miles walking home. A local account says there is very little information about Jesse Morgan, and that is still true. He died June 16, 1810 — the earliest death among the Revolutionary men at Elmwood. A 1929 survey placed his marble stone in the fourteenth row from the South Drive, marker 13, in the same row as Joseph Morgan. His service is taken from Sarah Rusk's 1980 record of Revolutionary patriots and their wives buried in Holyoke, reproduced by Canal Days. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_morgan_lucas",
   "name": "Morgan, Lucas",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Lucas Morgan enlisted October 21, 1776 in Captain Joseph Morgan's company of Colonel John Moseley's regiment and was discharged November 17 — twenty-eight days, the company marching under Lieutenant Colonel Timothy Robinson of Granville to reinforce the Northern Army, the roll dated at West Springfield. He was out again from September 21 to October 17, 1777 with the same company: one month and three days on the expedition to the northern department, six of those days and a hundred and twenty miles walking home. A local account says he was among the recruits Captain Joseph Morgan gathered as soon as the war broke out, and that they became part of the Third Hampshire regiment. The same account tells a story of a Morgan at the homestead on Northampton Street who came home one winter night to a horse that would not enter the stable, and found by touch that a man was crouched inside; he ran for the house and barred the heavy door, which rang with tomahawk blows until he fired a shot into the dark. In the morning there were the tracks of three men in the snow and the farm dog dead. The account attaches that story to Lucas and dates it 1741, which cannot be right — Rusk's record has him born in 1748. The story belongs to the family; which Morgan it belongs to has not been established. He died March 17, 1817. A 1929 survey placed his marble stone in the nineteenth row from the South Drive, marker 17. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  },
  {
   "id": "harper_rev_morgan_titus",
   "name": "Morgan, Titus",
   "era": "Revolutionary War",
   "branch": "",
   "branchLabel": "Revolutionary War",
   "lat": null,
   "lng": null,
   "photo": "",
   "narrative": "Titus Morgan enlisted October 20, 1777 in Captain Jonathan Bardwell's company of Colonel Elisha Porter's regiment and served one month and two and a half days with the Northern Army; the roll was dated at Deerfield. After the war he and his brother Erastus built a saw mill above the site of the present dam, and were the first men to use the water power at the rapids there — the power that everything Holyoke afterward became was built on. The mill later became part of the Connecticut Valley Lumber Company. He died March 30, 1831. A 1929 survey placed his marble stone in the twenty-seventh row from the South Drive, marker 21 — the last of the twenty-one, and the furthest from the drive. His service is taken from Sarah Rusk's 1980 record of Revolutionary patriots and their wives buried in Holyoke, reproduced by Canal Days. If you have further information about this veteran, please contact the City of Holyoke Veterans Graves Officer at (413) 322-5630 at 310 Appleton Street, 1st Floor, Holyoke, MA 01040.",
   "sourceNote": "Service record, from Wyatt E. Harper, The Story of Holyoke (published for the centennial of the City of Holyoke, 1973) — full researched narrative pending. Harper names him among the Revolutionary graves in this burial ground; the grave itself has not yet been located on the ground.",
   "badges": [],
   "status": "located",
   "source": "harper-revolutionary-graves"
  }
 ]
};
